id: P1CCCE706
initial_creation_type: input
source_metadata:
  title: Buddhagupta
  language: fr
  description: Instructions
  volume:
    d543115a3dcf49a3b2a44c20b6bf1b76:
      title: An Extensive Commentary on the Four Immeasurables
      parent: Instructions
created_at: '2022-03-01T02:13:36.519610'
last_modified_at: '2022-03-01T02:13:36.519612'
